dhsc-govuk/FingertipsNext

- .github/workflows/ci.yml
- README.md
- compose.yaml
- frontend/fingertips-frontend/.env.development
- frontend/fingertips-frontend/README.md
- frontend/fingertips-frontend/app/page.tsx
- frontend/fingertips-frontend/package-lock.json
- frontend/fingertips-frontend/package.json
- terraform/environment/container_app.tf
Make the frontend application query the API and show the details returned.
This is a very simple first version of the code to do this and will need refactoring into a more logical structure and to present the data better.
Changes:
- Re-enable the use of [GitVersion](https://gitversion.net/) in the CI workflow to generate a semantic version for each change (that is used to tag the container images produced)
- Add profiles to the Docker `compose.yaml` file, to allow a subset of services to be run. For example, to allow the API to be run while you work on the frontend
- Made the frontend call the API and display the weather forecasts returned
- Added the `FINGERTIPS_API_URL` environment variable to the Docker `compose.yaml` file, to allow the FE to communicate with the API when run locally
- …
> FTN-71: Make the frontend app query the API

- database/fingertips-db/fingertips-db.sqlproj
- frontend/fingertips-frontend/README.md
Following the existing readme.md to get up and running on a Windows laptop. 
1. NVM is a bit different on Windows, so I have changed readme.md to help people with a Windows laptop. 
2. Table script not added to Table folder in the sqlproject. 
3. CRLF changed to LF for the entrypoint.sh as that stops the docker container for sql running in Windows
> 2 changes to get the dev environment running in Windows.

- compose.yaml
This PR makes some tweaks to the `compose.yaml` file so that the application works again following the API refactoring done in #9.
- Updated the `FINGERTIPS_API_URL` environment variable passed to the frontend container to add the path to the WeatherForecast controller that is the one which returns data from the DB
- Updated the path to the API container's Dockerfile, now that it has been moved
I've verified that I am able to run `docker compose --profile all up --build --remove-orphans -d` locally and all containers start successfully:
Once they have started I am able to navigate to the frontend application and see that it has successfully retrieve data from the API:
> Fix compose.yaml following API refactor

- README.md
<h1>Description</h1>
This PR updates the docker compose down command in the README file, as the `profile` argument was placed in the wrong position, causing the command to fail. 
<h1>Changes</h1>
- Updated the `docker compose down` command and placed the `profile` argument in the right position.
> Fix docker compose down command in README

- README.md
- api/.dockerignore
- api/definition/swagger.yaml
As discussed I added the initial OpenApi 3.0.0 yaml definition file. This file should be used as a guide to implement the API. It can be edited directly or you can use a visual tool such as SwaggerHub or the 42crunch OpenApi Editor extension for VS Code. Can you review the file and see if it makes sense, for the time being
> Add design first OpenApi yaml file

- .gitattributes
Jira ticket: [DHSCFT-163](https://bjss-enterprise.atlassian.net/browse/DHSCFT-163?atlOrigin=eyJpIjoiMDRkZWI2Y2RiZDQ0NGEzYmJmODY3MDE0Yzk1ZDQyZDgiLCJwIjoiaiJ9)
Add .gitattributes file to set EOF for *.sh files to be LF.
Local functional check with:
```docker compose --profile all up --build --remove-orphans -d```
> add .gitattribute to configure EOF for .sh files to use LF

- frontend/fingertips-frontend/app/chart/page.tsx
Jira ticket: [DHSCFT-201](https://bjss-enterprise.atlassian.net/browse/DHSCFT-201)
The chart page was incorrectly using the searched indicator as the indicatorID to call the api and get healthData.
This should be the indicator selected and as part of the thin slice. This will just be the first indicator if there are multiples. 
All tests pass and ran manually.
Not tested against the real api but we would need to make sure that in the searchResults page the indicators returned have indicatorIds that return health data when we make the call to get health data.
> DHSCFT-201: use the first indicator selected to get healthData

- database/fingertips-db/PostDeployment/PopulateFingertips.sql
Jira ticket: None.
There is an issue with the database population script that means it fails when run a second time against an already-populated DB. This is due to the fact that we are not clearing the `Areas.Areas` table before population and are using fixed values for the `Node` primary key field in our population script.
- Add a `DELETE FROM` statement to `PopulateFingertips.sql` to clear the `Areas.Areas` table before populating it
Ran the `docker compose --profile all up --build --remove-orphans -d` command twice on `main`:
The db-setup container logs contained the following:
```
An error occurred while the batch was being executed.
Updating database (Failed)
*** Could not deploy package.
Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 2627, Level 14, State 1, Line 2 …
```
> [DHSCFT-TECH]: Clear the Areas.Areas table before populating it

- .github/workflows/fingertips-frontend-deploy.yml
Jira ticket: [DHSCFT-189](https://bjss-enterprise.atlassian.net/browse/DHSCFT-189)
Fix to the deployment pipeline to only deploy from completed builds on the main branch.
- Update deployment pipeline to only deploy from completed builds on the main branch
n/a
> Update deploy trigger for main branch only

- api/DHSC.FingertipsNext.Modules.Core.UnitTests/CoreControllerTests.cs
- api/DHSC.FingertipsNext.Modules.Core.UnitTests/DHSC.FingertipsNext.Modules.Core.UnitTests.csproj
- api/DHSC.FingertipsNext.Modules.HealthData.UnitTests/Controllers/V1/IndicatorsControllerTests.cs
- api/DHSC.FingertipsNext.Modules.HealthData.UnitTests/DHSC.FingertipsNext.Modules.HealthData.UnitTests.csproj
- api/DHSC.FingertipsNext.Modules.HealthData.UnitTests/ModuleTests.cs
- api/DHSC.FingertipsNext.Modules.HealthData.UnitTests/Repository/HealthDataRepositoryTests.cs
- api/DHSC.FingertipsNext.Modules.HealthData.UnitTests/Services/IndicatorServiceTests.cs
- api/DHSC.FingertipsNext.Modules.HealthData/DHSC.FingertipsNext.Modules.HealthData.csproj
Jira ticket: [DHSCT-213](https://bjss-enterprise.atlassian.net/browse/DHSCFT-213)
This ticket is to remove Fluent Assertions due to licensing changes and replace its functionality with Shouldly.
Fluent Assertions is limited to unit testing - these have all be executed and pass.
> DHSCT-213 - Shouldly migration

- .github/workflows/fingertips-frontend-deploy.yml
Jira ticket: [DHSCFT-208](https://bjss-enterprise.atlassian.net/browse/DHSCFT-208)
Just after my last PR merged in, another PR merged in removing the search bit of the url. But in the deploy job when we call the e2e test template we are still passing search in the env-url. This needs removing.
- Removing 'search' out of env-url passed to e2e test template job
Test on merge to main only
> DHSCFT-208 - remove search from url passed to test template

- .github/workflows/build-container.yml
- .github/workflows/fingertips-api-build.yml
- .github/workflows/fingertips-api-deploy.yml
- .github/workflows/fingertips-frontend-build.yml
- .github/workflows/fingertips-frontend-deploy.yml
Jira ticket: [DHSCFT-271](https://bjss-enterprise.atlassian.net/browse/DHSCFT-271)
Current builds are pushing images to a manually created ACR in Azure and use a username/password authentication. Refactoring is required in order to point a new ACR created in Terraform, then authenticate using Service Principal authentication. This change will also be reflected in the deployment workflows, to pull images.
- Update GitHub Action to a supported version
- Change authentication to use Service Principal authentication
- Update ACR login server to point at the new ACR created in Terraform
Branch has been run manually and is able to push the image successfully to the new ACR
> Change Azure Container Registry Server and Authentication Method

- .github/workflows/fingertips-api-deploy.yml
- .github/workflows/fingertips-frontend-deploy.yml
Jira ticket: [DHSCFT-209](https://bjss-enterprise.atlassian.net/browse/DHSCFT-209)
To be able to manually run a pipeline to trigger the e2e tests on deploy of frontend or api we needed this change
> DHSCFT-209_also_allow_e2e_tests_to_be_triggered_manually

- frontend/fingertips-frontend/package-lock.json
- frontend/fingertips-frontend/package.json
- frontend/fingertips-frontend/playwright.config.ts
Jira ticket: [DHSCFT-209](https://bjss-enterprise.atlassian.net/browse/DHSCFT-209)
As part of 209 we need the e2e test reliably and consistently passing when it is run after api and frontend deploys. This PR is to make that so.
- Set workers to 2 when in CI mode as recommended by playwright - [playwright docs](https://playwright.dev/docs/test-parallel#limit-workers)
- Double expect timeout in CI
CI e2e tests passed.
Will validate CD e2e once merged.
> DHSCFT-209_make_e2e_test_stable_after_deploy

- frontend/fingertips-frontend/playwright/tests/search_results_and_view_chart.spec.ts
Test out the work just merged in https://github.com/dhsc-govuk/FingertipsNext/pull/102 as discussed https://bjss.slack.com/archives/C085Q20RZU0/p1738253797006199?thread_ts=1738253729.474319&cid=C085Q20RZU0
- switch searched indicator in e2e test to 'Waiting' as this passes in CI but fails in CD
E2E tests pass in CI
> DHSCFT-281 switch indicator to something that passes in CI but failes in CD

- .github/workflows/e2e-tests.yml
Fix trailing double quotes at the end of the new slack command
> DHSCFT-281 - fix trailing double quotes

- .github/workflows/e2e-tests.yml
- .github/workflows/fingertips-api-deploy.yml
- .github/workflows/fingertips-frontend-deploy.yml
Fix to upload the new report so that the followon slack job can send it. see https://github.com/dhsc-govuk/FingertipsNext/actions/runs/13058665582/job/36436069494 for details where the e2e tests correctly failed and created a report:
playwright-ctrf-json-reporter: successfully written ctrf json to ctrf/ctrf-report.json
but then the slack job couldnt find it as it haddent been uploaded: 
Error: ENOENT: no such file or directory, open './frontend/fingertips-frontend/ctrf/ctrf-report.json'
> DHSCFT-281 fix upload of new report for slack job

- .github/workflows/e2e-tests.yml
In the previous [PR](https://github.com/dhsc-govuk/FingertipsNext/pull/108) i added a new step to download the new test report but forgot to add the condition to only run on failure+if an optional parameter has been passed in. This PR adds the condition in.
> DHSCFT-281 add condition to new download step

- .github/workflows/e2e-tests.yml
Add separate job to e2e to send slack notification
- Add separate job in e2e tests to download artifact and send notifications
> Add workflow job to e2e tests

- api/DHSC.FingertipsNext.Modules.HealthData/Controllers/V1/IndicatorsController.cs
- database/fingertips-db/PostDeployment/PopulateFingertips.sql
- frontend/fingertips-frontend/app/chart/page.test.tsx
- frontend/fingertips-frontend/app/chart/page.tsx
- frontend/fingertips-frontend/components/organisms/LineChartTable/LineChartTable.test.tsx
- frontend/fingertips-frontend/components/organisms/LineChartTable/__snapshots__/LineChartTable.test.tsx.snap
- frontend/fingertips-frontend/components/organisms/LineChartTable/index.tsx
- frontend/fingertips-frontend/components/pages/chart/index.tsx
- frontend/fingertips-frontend/lib/chartHelpers/chartHelpers.test.ts
- frontend/fingertips-frontend/lib/chartHelpers/chartHelpers.ts
- frontend/fingertips-frontend/mock/data/healthdata.ts
Jira ticket: [DHSCFT-226](https://bjss-enterprise.atlassian.net/browse/DHSCFT-226)
- Added API call to retrieve England benchmark data
- Displayed England data on Linechart table
- Added data to database post deploy script to enable testing with API
validated against API
> DHSCFT-226: Add England benchmark data to Linechart table

- frontend/fingertips-frontend/playwright/page-objects/pages/chartPage.ts
Jira ticket: [DHSCFT-340](https://bjss-enterprise.atlassian.net/browse/DHSCFT-340)
this fixes a known issue where we are expecting the e2e tests to fail du to expecting ‘populationPyramid-component’ to be visible but it is not visible.
this is because this [PR](https://github.com/dhsc-govuk/FingertipsNext/pull/136) removed the pop pyramid e2e check. but then when this [PR](https://github.com/dhsc-govuk/FingertipsNext/pull/138) has gone in after it, it has reintroduced the check.
ran tests locally using mocks and docker and both passed
running in CI passed
> DHSCFT-340 - add back in to not check pop pyramid is displayed

- frontend/fingertips-frontend/instrumentation.node.ts
- frontend/fingertips-frontend/instrumentation.ts
- frontend/fingertips-frontend/package-lock.json
- frontend/fingertips-frontend/package.json
Jira ticket: [DHSCFT-347](https://bjss-enterprise.atlassian.net/browse/DHSCFT-347)
Opentelemetry currently producing errors when loading telemetry within the NextJS application:
```
2025-02-14T13:29:01.387139621Z Error: @opentelemetry/api: Attempted duplicate registration of API: trace
2025-02-14T13:29:01.387166361Z     at registerGlobal (/app/node_modules/@opentelemetry/api/build/src/internal/global-utils.js:32:21)
2025-02-14T13:29:01.387175558Z     at TraceAPI.setGlobalTracerProvider (/app/node_modules/@opentelemetry/api/build/src/api/trace.js:54:59)
2025-02-14T13:29:01.387182040Z     at NodeTracerProvider.register (/app/node_modules/@opentelemetry/sdk-trace-base/build/src/BasicTracerProvider.js:101:21)
2025-02-14T13:29:01.387188713Z     at NodeTracerProvider.register …
```
> Fix open telemetry registration

- frontend/fingertips-frontend/components/organisms/AreaFilter/__snapshots__/AreaFilter.test.tsx.snap
- frontend/fingertips-frontend/components/organisms/AreaFilter/index.tsx
- frontend/fingertips-frontend/playwright/page-objects/pages/resultsPage.ts
- frontend/fingertips-frontend/playwright/tests/search_results_and_view_chart.spec.ts
This reverts #169.
Jira ticket: [DHSCFT-236](https://bjss-enterprise.atlassian.net/browse/DHSCFT-236)
The test changes in #169 are causing issues when run against the deployed environment. There are also some questions around whether we should be doing all this testing at E2E level (and with fixed data). Reverting for now, and these tests will be reinstated by @williamwillis11 in DHSCFT-291.
- Revert 842b871
Ensure E2E tests still pass in the CI workflow.
> DHSCFT-236: Revert "e2e test added (#169)"

- frontend/fingertips-frontend/app/results/page.test.tsx
- frontend/fingertips-frontend/app/results/page.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSelectionForm/indicatorSelectionForm.test.tsx
- frontend/fingertips-frontend/components/molecules/result/searchResult.test.tsx
- frontend/fingertips-frontend/components/pages/results/Results.test.tsx
- frontend/fingertips-frontend/lib/search/indicatorSearchService.test.ts
- frontend/fingertips-frontend/lib/search/indicatorSearchService.ts
- frontend/fingertips-frontend/lib/search/indicatorSearchServiceMock.test.ts
- frontend/fingertips-frontend/lib/search/indicatorSearchServiceMock.ts
- frontend/fingertips-frontend/lib/search/searchTypes.ts
Jira ticket: [DHSCFT-51](https://bjss-enterprise.atlassian.net/browse/DHSCFT-51)
- Updates the results page to pass the areasSelected to the searchWith function.
- Updates the mockIndicatorData to have associatedAreaCodes for indicator 108
- Updates the indicator to AI search to do the same for 108
Changes to indicator.json
Tests passing.
Manually tested against the mock AI search
Manually tested against the real AI search
> DHSCFT-51: update searchWith to use selected area codes

- .github/workflows/e2e-tests.yml
- frontend/fingertips-frontend/package.json
- frontend/fingertips-frontend/playwright.config.ts
Jira ticket: [DHSCFT-291](https://bjss-enterprise.atlassian.net/browse/DHSCFT-291)
Followup fix for an issue introduced in the first PR for 291 - https://github.com/dhsc-govuk/FingertipsNext/pull/181
- changed config to only spin up a dev server if the FINGERTIPS_FRONTEND_URL isnt passed
- added new npm command to run the e2e tests against azure
- pointed the e2e yml template to use this new command
ui tests pass locally
e2e tests pass against docker locally
both pass in CI
> DHSCFT-291_fix_for_e2e_CD

- frontend/fingertips-frontend/lib/areaFilterHelpers/determineApplicableGroupTypes.test.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/determineApplicableGroupTypes.ts
Jira ticket: [DHSCFT-255](https://bjss-enterprise.atlassian.net/browse/DHSCFT-255)
Added default option of "England" to Group Type dropdown.
- Added a condition to return "England" as the group type for the area type of England
- Amended test to match new expected behaviour
Updated unit tests to cater for this change. All test passing.
> DHSCFT-255 - Added default option for Group Type dropdown

- database/fingertips-db/PostDeployment/PopulateFingertips.sql
Jira ticket: [DHSCFT-439](https://bjss-enterprise.atlassian.net/browse/DHSCFT-439)
When inserting indicators ino the IndicatorDimension table trim trailing charcetrs and remove double quotes.
Run the db-setup container and check the results in the database.
> fix an issue with trailing spaces in indicator names

- frontend/fingertips-frontend/lib/areaFilterHelpers/areaType.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/determineApplicableGroupTypes.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/determineSelectedGroupType.test.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/determineSelectedGroupType.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/getAreaFilterData.ts
Jira ticket: [DHSCFT-438](https://bjss-enterprise.atlassian.net/browse/DHSCFT-438)
- Align Area Type data with the API
- Fix groupType to be autopicked from the first availableGroupTypes
All tests passing. Tested against the real api. Area filtering working as expected
> DHSCFT-438: fix for real api data

- .github/workflows/e2e-tests.yml
Jira ticket: [DHSCFT-287](https://bjss-enterprise.atlassian.net/browse/DHSCFT-287)
By design we arnt running the screenshot comparison checks in the e2e test run against azure (in CD) but i forgot in https://github.com/dhsc-govuk/FingertipsNext/pull/203 to add a rule to that step to stop that job from running. This PR adds that.
kicked off a pipeline here (as yml changes dont) - https://github.com/dhsc-govuk/FingertipsNext/actions/runs/13696786879
> DHSCFT-287 fix to not run the create screenshot job in CD

- frontend/fingertips-frontend/components/organisms/LineChartTable/__snapshots__/LineChartTable.test.tsx.snap
- frontend/fingertips-frontend/components/organisms/LineChartTable/index.tsx
- frontend/fingertips-frontend/components/views/OneIndicatorOneAreaView/OneIndicatorOneAreaView.test.tsx
- frontend/fingertips-frontend/components/views/OneIndicatorOneAreaView/index.tsx
DHSCFT-142: Benchmark labels in the Line Chart Table
Jira ticket: [DHSCFT-142](https://bjss-enterprise.atlassian.net/browse/DHSCFT-142)
Benchmark labels
- Added benchmark labels to the line chart table
Polarities and benchmark group types still need to come from the api but not yet implemented, so the above screenshots are manipulated to demo the variants which will be available.
> DHSCFT-142: line chart table benchmark colours rag

- frontend/fingertips-frontend/components/molecules/TrendTag/index.tsx
- frontend/fingertips-frontend/components/molecules/TrendTag/trendTag.test.tsx
- frontend/fingertips-frontend/components/molecules/TrendTag/trendTagConfig.ts
- frontend/fingertips-frontend/lib/common-types/index.ts
https://bjss-enterprise.atlassian.net/browse/DHSCFT-457
add "data not available" to the existing set of trend tags
unit tested like the rest of them.
> add trend not available tag

- .github/workflows/fingertips-workflow.yml
The table definitions are loaded in our SQL project before the post-deployment script runs. We had an issue where we had updated a table to specify that a column should be NOT NULL, but there was already existing data which was NULL.
`p:GenerateSmartDefaults=true`  Adding this resolves the error, as it will set a value instead of falling over. I think this is ok, as the PostDeployment script deletes all data and then reloads fresh each time. However, I'm equally open to us deleting/adjusting data manually before this is job is run on this particular occasion.
On the second commit, I allowed this to be run from this branch. Here is the successful pipeline: https://github.com/dhsc-govuk/FingertipsNext/actions/runs/13808202768/job/38623655433
> DHSCFT-446: Fix db deployment

- terraform/locals.container-app.tf
- terraform/variables.tf
Change minimum replicas on container apps from 0 to 1 to prevent scaling to 0.
- Change default minimum replicas
- Remove CPU scaling rule (by default it will scale on incoming requests)
> Container App Minimum Replicas

- frontend/fingertips-frontend/components/forms/IndicatorSearchForm/IndicatorSearchForm.test.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSearchForm/indicatorSearchActions.test.ts
- frontend/fingertips-frontend/components/forms/IndicatorSearchForm/indicatorSearchActions.ts
- frontend/fingertips-frontend/components/molecules/SelectAreasFilterPanel/SelectAreasFilterPanel.test.tsx
- frontend/fingertips-frontend/components/molecules/SelectAreasFilterPanel/index.tsx
- frontend/fingertips-frontend/components/molecules/SelectedAreasPanel/SelectedAreasPanel.test.tsx
- frontend/fingertips-frontend/components/molecules/SelectedAreasPanel/index.tsx
Jira ticket: [DHSCFT-358](https://bjss-enterprise.atlassian.net/browse/DHSCFT-358)
Added removal of indicators from URL when the area selected gets updated either by:
- selecting a new area
- deselecting an existing selected area via removal of pill
- deselecting an existing selected area by unchecking checkbox on filter panel
- clearing the search 
- Added removal of indicators from URL on indicatorSearchActions, SelectAreasFilterPanel and SelectedAreasPanel
- Added unit tests to cover the change
Added new unit tests to verify the correct functionality
> DHSCFT-358 - Clear indicator(s) selected on search change

- api/definition/swagger.yaml
No ticket, direct request from Fawad.
- Make BadRequest schema be a schema rather than a response so that we can use examples to document likely errors returned by api
- Other syntax adjustments so that swagger validation was clean in swaggerhub and my local dev tools.
Output of generate:api-client looks mostly identical to what was in git/main, but there are some changes that appear to be due to other swagger changes that hadn't been generated yet.
After a `generate:api-client` all unit tests still pass and a basic walk through the search/results pages looks OK.
> Tweak swagger file to un-break generate:api-client

- frontend/fingertips-frontend/app/(home)/page.test.tsx
- frontend/fingertips-frontend/app/(home)/page.tsx
- frontend/fingertips-frontend/app/chart/page.test.tsx
- frontend/fingertips-frontend/app/chart/page.tsx
- frontend/fingertips-frontend/app/results/page.test.tsx
- frontend/fingertips-frontend/app/results/page.tsx
- frontend/fingertips-frontend/components/views/OneIndicatorOneAreaView/OneIndicatorOneAreaView.test.tsx
- frontend/fingertips-frontend/components/views/OneIndicatorOneAreaView/index.tsx
- frontend/fingertips-frontend/components/views/OneIndicatorTwoOrMoreAreasView/OneIndicatorTwoOrMoreAreasView.test.tsx
- frontend/fingertips-frontend/components/views/OneIndicatorTwoOrMoreAreasView/index.tsx
- frontend/fingertips-frontend/lib/apiClient/apiClientFactory.test.ts
- frontend/fingertips-frontend/lib/apiClient/apiClientFactory.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/getAreaFilterData.test.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/getAreaFilterData.ts
Jira ticket: [DHSCFT-468](https://bjss-enterprise.atlassian.net/browse/DHSCFT-468)
Adds caching config to all api requests for 1 hour before revalidating
Tested locally - first requests to an endpoint will fetch from the API. Subsequent requests to the same endpoint will fetch from cache
> DHSCFT-468: cache api request on FE

- .github/workflows/fingertips-workflow.yml
- compose.yaml
- trend-analysis/TrendAnalysisApp/Dockerfile
Jira ticket: [DHSCFT-367](https://bjss-enterprise.atlassian.net/browse/DHSCFT-367)
Extend GH Actions pipeline and local docker compose so that trend analysis will be executed.
- Compose: post db-setup completing, then the new job will be executed. A Dockerfile has been added to the trend-analysis directory to run the command.
- Github Actions pipeline: the logic I ended up with is that we only want to execute the trend analysis in the pipeline if a change has been made to the DB. I.e. the data will have loaded fresh with the default trend values so trends will need to be recalculated.
- In addition to this, I have ensured that A. the Trend Analysis unit tests also get run if the DB has been changed, since this means the trend analysis will be run, so it's nice to check even if nothing in …
> DHSCFT-367: Pipeline step for trends

- api/DHSC.FingertipsNext.Modules.Area.Repository/AreaRepository.cs
Jira ticket: [DHSCFT-476](https://bjss-enterprise.atlassian.net/browse/DHSCFT-476)
This provides some further optimisation to the GetDescendants SQL query by having the recursive SQL exit early when it can.
Tests suggest a 30% performance improvement.
- Update GetDescendants recursive SQL to exit once the areaType level is higher value than the target level
- Or to exit if the Hierarchy type is not equal to the target heirarchyType
Tests have been performed on getting descendants of England for each area type and comparing main against the feature branch. See attached word doc.
> DHSCFT-476: Optimise GetDescendants

- .github/workflows/fingertips-workflow.yml
Pipelines failing on database deploy job due to long file paths in the git repo. Fix the git config on Windows hosted runner to enable long file path support
- Enable long file paths before git checkout on the Windows runner
> Enable long paths

- .github/workflows/fingertips-workflow.yml
Remove the default directorywithin the database deploy job which is preventing long file paths from being enabled
- Remove default directory within database deploy job
Tested workflow manually against the branch and I'm able to enable long file paths and deploy the dacpac
> Remove default branch

- .github/workflows/fingertips-workflow.yml
Add missing workflow dependencies to wait for jobs to complete before starting
- Add dependency on db deploy to wait for API build and e2e tests
- Add dependency on CD e2e tests to wait for trend analysis
> Add workflow dependencies

- .github/workflows/fingertips-workflow.yml
- trend-analysis/TrendAnalysisApp/Constants.cs
- trend-analysis/TrendAnalysisApp/Program.cs
Jira ticket: [DHSCFT-488](https://bjss-enterprise.atlassian.net/browse/DHSCFT-488)
First time running in the pipeline after parallelizing, we ran into an issue where one of the threads had a SQL query timeout issue. The assumption is that because it is now running in parallel the DB is under greater strain and one of the threads took more than the default 30 seconds.
Therefore bumped up the timeout. We allowed running from this branch in the initial commit so we could do some testing:
https://github.com/dhsc-govuk/FingertipsNext/actions/runs/13924455569/job/38971302889
It completed in 5 minutes rather than the 8-9 minutes that it was taking previously.
This PR also introduces a more stringent if statement for the job.
Ran test pipeline against this branch.
> DHSCFT-488: Increase timeout for trend processing in pipeline

- frontend/fingertips-frontend/lib/areaFilterHelpers/areaTypeSorter.test.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/areaTypeSorter.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/getAreaFilterData.test.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/getAreaFilterData.ts
Jira ticket: [DHSCFT-450](https://bjss-enterprise.atlassian.net/browse/DHSCFT-450)
Changed the sorting of the AreaType dropdown so that it gets sorted by Hierarchy and by Level within the hierarchy.
- Added new helper class areaTypeSorter 
- Updated getAreaFilterData to use new helper class function
- Updated getAreaFilterData 
- Added new unit test class for new helper
Added a new set of unit tests as well as updated the existing one that checked the sorting of this dropdown.
> DHSCFT-450 - Sort AreaType in area type dropdown by Hierarchy and Level

- frontend/fingertips-frontend/playwright/tests/isolated_ui_tests/navigation_and_validation.spec.ts
Jira ticket: [DHSCFT-489](https://bjss-enterprise.atlassian.net/browse/DHSCFT-489)
Added new e2e test to cater for the changes made as part of DHSCFT-358
- Added new test to ensure the URL is updated correctly to remove any selected indicators when the search changes.
New test added and passing
> DHSCFT-489 - Add e2e test for clearing indicator on search change

- frontend/fingertips-frontend/playwright/testHelpers.ts
Jira ticket: [DHSCFT-505](https://bjss-enterprise.atlassian.net/browse/DHSCFT-505)
in DHSCFT-434: Fix inequalities functionality with real data - @Gareth Allan fixed an api issue that means i can safely remove some defensive filters from filterIndicatorsByName
E2E and UI tests continue to pass
> DHSCFT-505 Remove defensive filters from filterIndicatorsByName

- frontend/fingertips-frontend/playwright/page-objects/pageFactory.ts
Jira ticket: [DHSCFT-536](https://bjss-enterprise.atlassian.net/browse/DHSCFT-536)
Since this morning, e2e tests (CD against deployed site) have been failing consistently.
To get to this change, I was running the `npm run test-e2e-ci-azure` against my locally running Docker setup. However, once DB deployments are complete I'll also try pointing it at the deployed environment.
**Cause:**
- When navigating to the 1 Indicator All areas in group page (which has the map and per area bar chart) an exception to do with Highcharts seems to be registered on the page.
- It is weird because I cannot see this when checking the console in the browser - all looks fine. Anyway, by surfacing the stack trace I was able to identify the full message and that it's something to do with Highcharts: …
> DHSCFT-536: proposed fix for failing e2e tests

- trend-analysis/TrendAnalysisApp.UnitTests/TrendDataProcessorTests.cs
- trend-analysis/TrendAnalysisApp/Constants.cs
Jira ticket: NA Tech ticket
Since a recent change went into the DB, some of the indexes for the dimensions have changed.
This resulted in the Azure AI Search returning trendsForAreas as always an empty list (you can test this against the dev AI Search index). It demonstrates some of the limitations of my PoC approach for this, hopefully the indicator, age and sex dimension keys won't change again. But it does show that a more sustainable approach may need to be taken in future e.g. retrieving based on string value. However, unless the trend calculation is moved elsewhere we will always require some config data.
My change fixes the constants up to match the updated keys.
Ran it locally and verified you now get trend data generated.
> DHSCFT-TECH: Updated the hardcoded indexes in trend-analysis

- .github/workflows/ui-tests.yml
- frontend/fingertips-frontend/package.json
- frontend/fingertips-frontend/playwright.config.ts
Jira ticket: [DHSCFT-495](https://bjss-enterprise.atlassian.net/browse/DHSCFT-495)
Change playwright tests to use Next build and start rather than dev.
add new script to package.json to start with local mocks
change playwright config to build and start. Also, increase timeout for webserver to allow for build time
pass configuration variables in github action
npm run test-ui-local-mocks and npm run test-e2e-ci-azure (with local api) pass all tests.
> use build and start for playwright tests

- api/DHSC.FingertipsNext.Modules.HealthData.Schemas/IndicatorWithHealthDataForAreas.cs
- api/DHSC.FingertipsNext.Modules.HealthData.Service/IndicatorService.cs
- api/definition/swagger.yaml
- frontend/fingertips-frontend/generated-sources/ft-api-client/models/IndicatorWithHealthDataForArea.ts
- frontend/fingertips-frontend/mock/server/handlers.ts
Jira ticket: [DHSCFT-542](https://bjss-enterprise.atlassian.net/jira/software/projects/DHSCFT/boards/823?assignee=557058%3A5e651a12-82ba-4f1e-b0d5-debb80721a37)
Adds indicator ID into the response from the health data endpoint
All tests pass and manually validated by calling the API.
> Add indicator ID to health data endpoint

- trend-analysis/TrendAnalysisApp/Constants.cs
- trend-analysis/TrendAnalysisApp/Repository/HealthMeasureRepository.cs
- trend-analysis/TrendAnalysisApp/TrendDataProcessor.cs
Jira ticket: [DHSCFT-556](https://bjss-enterprise.atlassian.net/browse/DHSCFT-556)
Increases robustness and reliability of the trend analysis app.
- Main change is to skip trend analysis calculation for the indicators as discussed here: https://bjss.slack.com/archives/C08335HN952/p1743409304149789 Specifically that is `337` and `92708`. I am using the Fingertips IndicatorIds rather than key as I find this varies sometimes between local and deployed DB. IndicatorId is reliably constant.
There is an additional change for a bug I noticed. Occasionally when the job fails we have to rerun it. A while back, I had the application skip calculating trends if it saw that the trend had already been calculated. This failed to take into account reruns. At the time it was not an issue, but since we …
> DHSCFT-556: Skip full population indicators for trend analysis

- frontend/fingertips-frontend/package-lock.json
- frontend/fingertips-frontend/package.json
Jira ticket: [DHSCFT-557](https://bjss-enterprise.atlassian.net/browse/DHSCFT-557)
pinned openapi-generator-cli to 2.18.3 as 2.18.4 has a vuln:
https://github.com/dhsc-govuk/FingertipsNext/security/dependabot/8
- pinned openapi-generator-cli to 2.18.3
All tests pass
ran the local script without failure: npm run generate:api-client
> DHSCFT-557 pin openapi-generator-cli to last known good version

- frontend/fingertips-frontend/components/molecules/Inequalities/BarChart/index.tsx
Jira ticket: [DHSCFT-555](https://bjss-enterprise.atlassian.net/browse/DHSCFT-555)
Adjust the inequalities bar chart tooltip positioning so that it displays correctly for both the sex and deprivation charts.
- Updated the `tooltipPos` value of the benchmark plotline's custom tooltip to use the same calculation as the `plotX` value. I found when debugging that the tooltip was showing for the deprivation chart, but the `tooltipPos` value was much too high and resulted in it display quite a way to the right of the benchmark line. This change results in the tooltip displaying to the left of the line, which seems to work well.
I can't get screenshots to capture the tooltip, but you can try it out yourself.
Sex chart on main: http://20.26.160.30/chart?si=22401&is=22401&ats=england&gts=england&gs …
> DHSCFT-555: Make bar chart tooltip display for the deprivation chart

- frontend/fingertips-frontend/components/molecules/Inequalities/InequalitiesForSingleTimePeriod/index.tsx
Jira ticket: [DHSCFT-555](https://bjss-enterprise.atlassian.net/browse/DHSCFT-555)
When merging #346 the `type` property was inadvertently removed from the properties passed to the `InequalitiesBarChart` component. This means that the deprivation chart is shown at a very small size.
- Pass type property to InequalitiesBarChart component again
Chart on `main` ([link](http://20.26.160.30/chart?si=22401&is=22401&ats=england&gts=england&gs=E92000001&gas=ALL&its=deprivation)):
Chart with these changes:
> DHSCFT-555: Fix deprivation bar chart display

- frontend/fingertips-frontend/components/forms/IndicatorSelectionForm/index.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSelectionForm/indicatorSelectionForm.test.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSort/IndicatorSort.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSort/indicatorSort.types.ts
- frontend/fingertips-frontend/components/forms/IndicatorSort/useIndicatorSort.test.ts
- frontend/fingertips-frontend/components/forms/IndicatorSort/useIndicatorSort.ts
- frontend/fingertips-frontend/lib/search/indicatorSearchService.test.ts
- frontend/fingertips-frontend/lib/search/indicatorSearchService.ts
- frontend/fingertips-frontend/lib/search/indicatorSearchServiceMock.ts
- frontend/fingertips-frontend/lib/searchStateManager.ts
Jira ticket: [DHSCFT-176](https://bjss-enterprise.atlassian.net/browse/DHSCFT-176)
Add sort order dropdown to the indicator results page
- Added hook for sorting
- Added component to show the dropdown/select
> DHSCFT-176: Result sort order

- frontend/fingertips-frontend/app/results/page.test.tsx
- frontend/fingertips-frontend/app/results/page.tsx
Jira ticket: [DHSCFT-527](https://bjss-enterprise.atlassian.net/browse/DHSCFT-527)
Resolves the issue where we weren't filtering the search results by area when you had selected all areas in a group.
- Made the results page use the available areas to filter search results (instead of the selected areas) when the `gas` query parameter is set to `ALL`
Running locally in Docker, selecting all areas in a group no longer causes the indicator to appear (it did before these changes):
> DHSCFT-527 - Filter search results by area when selecting all areas in a group

- frontend/fingertips-frontend/components/organisms/SparklineChart/SparklineChart.test.tsx
- frontend/fingertips-frontend/components/organisms/SparklineChart/index.tsx
Jira ticket: [DHSCFT-551](https://bjss-enterprise.atlassian.net/browse/DHSCFT-551)
- Refactored the `sparklineTooltipContent` function to shown quintile values in hover
Showing not compared
Showing worst quintile
Showing better quintile
> DHSCFT-551: Add quintiles to the sparkline chart hover

- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTableRow.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTableRow.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/index.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/spineChartTableHelpers.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/spineChartTableHelpers.tsx
- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsAreasViewPlots/TwoOrMoreIndicatorsAreasViewPlots.test.tsx
- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsAreasViewPlots/index.tsx
Jira ticket: [DHSCFT-634](https://bjss-enterprise.atlassian.net/browse/DHSCFT-634)
Stopped spine charts from crashing if there is data missing
- Returned null in place of throwing an error
- Filtered out null results
Began updating code to show X's when data was missing, but this turned out to be a much bigger issue than simply omitting the incomplete row data altogether.
http://20.26.160.30/chart?si=age&is=30302&is=20401&as=E12000004&as=E12000006&ats=regions&gts=england&gs=E92000001&iys=2015
Indicator: "Hepatitis B vaccination coverage aged 2 years" is missing in the spine chart table illustrated below as there is missing data.
> DHSCFT-634: omit rows from spine chart table if any data is not found

- frontend/fingertips-frontend/components/organisms/SparklineChart/index.tsx
Jira ticket: [DHSCFT-650](https://bjss-enterprise.atlassian.net/browse/DHSCFT-650)
- Default bar colour to white unless the area is England
> DHSCFT-650: Bugfix - only the England bar should be dark grey

- frontend/fingertips-frontend/components/forms/IndicatorSort/useIndicatorSort.test.ts
- frontend/fingertips-frontend/components/forms/IndicatorSort/useIndicatorSort.ts
Jira ticket: [DHSCFT-638](https://bjss-enterprise.atlassian.net/browse/DHSCFT-638)
Indicator searches were client side limited to 20 display results. This limit is being removed for the POC.
- Removed the 20 indicator limit from `useIndicatorSort`.
Quick run of the app plus check all the automated tests.
> DHSCFT-638 remove 20 indicator limit

- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsAreasViewPlots/TwoOrMoreIndicatorsAreasViewPlots.test.tsx
- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsAreasViewPlots/index.tsx
Jira ticket: [DHSCFT-652](https://bjss-enterprise.atlassian.net/browse/DHSCFT-652)
We had not coded for this scenario and this was highlighted in the demo.
- Added extra logic to check for the `SearchParams.GroupAreaSelected` value and render accordingly
- Added additional unit test for this scenario
Tested locally and also ran a regression checking all the other scenarios documented in the ticket.
> DHSCFT-652: Only show heatmap when all areas in group selected

- frontend/fingertips-frontend/components/views/ViewsContext.test.tsx
https://bjss-enterprise.atlassian.net/browse/DHSCFT-612
the api calls from the pop pyramid were causing noise in the views context tests - mocked out in a similar way to the individual views as we don't really care about it in these tests
> DHSCFT-612 fix viewscontext console noise

- .github/workflows/e2e-and-api-tests.yml
- api/DHSC.FingertipsNext.Modules.Area/HttpClientScripts/test-areas-multiple-areas.http
- api/DHSC.FingertipsNext.Modules.HealthData/HttpClientScripts/test-indicators-benchmark-quintiles.http
- api/README.md
Jira ticket: [DHSCFT-661](https://bjss-enterprise.atlassian.net/browse/DHSCFT-661)
See linked pipeline in ticket. We found that the output of the API test is truncated and it is also very difficult to identify what actually went wrong. This PR aims to improve this.
- Updates the command that is run in the pipeline. The command will now 1. only show the failed output and overall summary (much less verbose) 2. show the full failing API response
- Adds a couple of improvements to one test file to ensure that errors are surfaced correctly
- Adds details to the Readme to make the usage and intent of httpyac clearer
I created some failing tests so we can validate that A. the pipeline fails and B. the output is improved.
You can see the results of that pipeline run here: …
> DHSCFT-TECH: Improve API test output

- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsAreasViewPlots/TwoOrMoreIndicatorsAreasViewPlots.test.tsx
Jira ticket: [DHSCFT-625](https://bjss-enterprise.atlassian.net/browse/DHSCFT-625)
Does what it says on the tin. Removes the duplicate keys due to us repeating the area name in the test data.
> DHSCFT-625: Removed console logs in two indicators multiple areas tests

- frontend/fingertips-frontend/components/organisms/SpineChart/SpineChart.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChart/SpineChartOptions.ts
Jira ticket: [DHSCFT-667](https://bjss-enterprise.atlassian.net/browse/DHSCFT-667)
Change markers to white
- Change markers to white when there is no benchmark data
> DHSCFT-667: spine chart shapes should be white when benchmarking is undefined or Not Compared

- frontend/fingertips-frontend/components/forms/IndicatorSearchForm/indicatorSearchActions.ts
- frontend/fingertips-frontend/components/forms/SearchForm/searchActions.test.ts
- frontend/fingertips-frontend/components/forms/SearchForm/searchActions.ts
- frontend/fingertips-frontend/components/pages/home/index.tsx
Jira ticket: [DHSCFT-595](https://bjss-enterprise.atlassian.net/browse/DHSCFT-595)
Clear selected indicators when the user actions a new search from the homepage
- When the `searchAction` on the homepage is actioned, remove selected indicators from search state before generating results page url.
Ran the unit tests. Manually check the scenario in the video.
> DHSCFT-595: Clear selected indicators for a new home page search

- frontend/fingertips-frontend/components/organisms/BenchmarkLabel/BenchmarkLabelConfig.ts
- frontend/fingertips-frontend/components/organisms/BenchmarkLabel/index.tsx
Jira ticket: [DHSCFT-667](https://bjss-enterprise.atlassian.net/browse/DHSCFT-667)
- default benchmark colours are Not Defined
> DHSCFT-667: Benchmark label white when not compated

- api/DHSC.FingertipsNext.Modules.Area/Controllers/V1/AreaController.cs
- api/DHSC.FingertipsNext.Modules.HealthData.Repository/HealthDataPredicates.cs
- api/DHSC.FingertipsNext.Modules.HealthData.Repository/HealthDataRepository.cs
- api/DHSC.FingertipsNext.Modules.HealthData.Repository/IHealthDataRepository.cs
- api/DHSC.FingertipsNext.Modules.HealthData.Service/IndicatorService.cs
- api/DHSC.FingertipsNext.Modules.HealthData.UnitTests/Repository/HealthDataRepositoryTests.cs
- api/DHSC.FingertipsNext.Modules.HealthData.UnitTests/Services/IndicatorServiceTests.cs
- api/DHSC.FingertipsNext.Modules.HealthData/Controllers/V1/IndicatorsController.cs
- api/definition/swagger.yaml
- frontend/fingertips-frontend/app/chart/PopulationPyramidWithTableDataProvider/PopulationPyramidWithTableDataProvider.test.tsx
- frontend/fingertips-frontend/generated-sources/ft-api-client/apis/AreasApi.ts
- frontend/fingertips-frontend/generated-sources/ft-api-client/apis/IndicatorsApi.ts
- frontend/fingertips-frontend/lib/ViewsHelpers.test.ts
- frontend/fingertips-frontend/lib/ViewsHelpers.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/getSelectedAreasData.test.tsx
- frontend/fingertips-frontend/lib/chunkArray.ts
Jira ticket: [DHSCFT-662](https://bjss-enterprise.atlassian.net/browse/DHSCFT-662)
Ensure we return data for the latest year when requested, scoped to the area codes provided by the client and excluding the latest date for England.
- Upped the chunking limit to 300 for both the indicator data and areas API endpoints. This means that the largest collection i.e. all districts for England should not be chunked up which avoids the issue (edge case) where a set of areas might have a different latest year to another. (Due to the way data is collected this is unlikely but worth guarding against).
- Extended backend repository method so the latest year will be considering the area codes provided and will exclude England for the reasons articulated on the ticket.
- Added required additional tests …
> DHSCFT-662: Improve get latest data functionality

- DataCreator/DataCreator/DataFileReader.cs
- DataCreator/DataCreator/DataFileWriter.cs
Jira ticket: None.
This PR makes updates to the DataCreator application so that it can be run on Mac.
- Replaced string literal paths with use of [`Path.Join`](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.join?view=net-9.0), so they are not always separated with `\`
Deleted the contents of the `DataCreator/DataCreator/data/out` directory, ran the application using the latest Pholio DB export and without changing the other input data files, then verified using git that the files produced in `DataCreator/DataCreator/data/out` were unchanged.
@HowardMayBjss has also verified that he is able to perform the above verification on Windows.
> Update DataCreator paths to work on Mac

- frontend/fingertips-frontend/components/organisms/SpineChart/SpineChartOptions.ts
Jira ticket: [DHSCFT-668](https://bjss-enterprise.atlassian.net/browse/DHSCFT-668)
- Add 'than England' to the spine chart hovers
> Bugfix/dhscft 668 add `than England` to the hovers

- frontend/fingertips-frontend/lib/chartHelpers/chartHelpers.test.ts
- frontend/fingertips-frontend/lib/chartHelpers/chartHelpers.ts
Jira ticket: [DHSCFT-689](https://bjss-enterprise.atlassian.net/browse/DHSCFT-689)
Replication steps can be seen on the ticket. You can check out this branch, run the same steps and see that the plot line for England has returned.
This fixes the problem by putting in appropriate handling for when there is no area data.
I had hoped screenshot testing would catch this, but I think all the Line Chart screenshots include an area, region and England. Could be a nice test to have in future to avoid regression?
It is valid that a user may reach this page having not yet selected an area other than England, which is there by default.
We had no checking that the array for area data (which excludes England) was not empty. This resulted us running `Math.max(...[])` and `Math.min([])` which resolve to …
> DHSCFT-689: Line chart plot not showing when only England

- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTableRow.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTableRow.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/index.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/spineChartTableHelpers.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/spineChartTableHelpers.tsx
Jira ticket: [DHSCFT-694](https://bjss-enterprise.atlassian.net/browse/DHSCFT-694)
- Include spine chart row in table even if an area is missing data
- Pull out the show two areas so that the row is told rather than deduce from the data, as if the data is missing it would render alternate layout for a single area
Before row missing...
Showing the row but not forcing the row into multiple area rendering view...
After, note the second row is showing but has X for Derbyshire and only shows one marker on the spine
When the only area is missing
> DHSCFT-694: Show spine chart row when an area is missing

- frontend/fingertips-frontend/components/organisms/Inequalities/inequalitiesHelpers.test.ts
- frontend/fingertips-frontend/components/organisms/Inequalities/inequalitiesHelpers.ts
Jira ticket: [DHSCFT-696](https://bjss-enterprise.atlassian.net/browse/DHSCFT-696)
Filter inequalities CIs within first and last year to be consistent with series.
- Add filter to `generateConfidenceIntervalSeries()`
Behaviour as expected against local api:
http://localhost:3000/chart?si=22401&is=22401&ats=england&gts=england&gs=E92000001&gas=ALL&ilts=Districts+and+Unitary+Authorities+deprivation+deciles%3A+Apr+2023+geography+%28Index+of+Multiple+Deprivation+2019%29
> DHSCFT-696_ghost_CIs_for_inequalities_trend

- frontend/fingertips-frontend/playwright/page-objects/pages/chartPage.ts
- frontend/fingertips-frontend/playwright/testHelpers.ts
Jira ticket: [DHSCFT-703](https://bjss-enterprise.atlassian.net/browse/DHSCFT-703)
Added functionality to tick the Confidence Interval checkbox for inequalitiesForSingleTimePeriodComponent and inequalitiesTrendComponent on the core journey tests
- Added logic to chartPage to determine correct locator for CI checkbox
- Added flag for confidence interval to inequalitiesForSingleTimePeriodComponent and inequalitiesTrendComponent  components
Existing test expanded to include the ticking of the checkbox
Manually checked ticking of the boxes through test runs (screenshots not regenerated due to current ongoing work on threshhold)
> DHSCFT-703 - Turn ticking CI checkbox ON for Inequalities on Chart components

- frontend/fingertips-frontend/playwright/page-objects/pageFactory.ts
Jira ticket: [DHSCFT-537](https://bjss-enterprise.atlassian.net/browse/DHSCFT-537)
Investigate, and if necessary/possible fix the unhandled exception from highcharts that was causing playwright tests to fail.
- Removed code, added as a temporary workaround, that swallowed the exception.
Ran the tests locally a few times, and in the pipeline. Error not present during testing. Decision made assume the issue has been resolved and see if it returns.
> DHSCFT-537 - highcharts exception in e2e tests

- frontend/fingertips-frontend/components/forms/IndicatorSelectionForm/index.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSelectionForm/indicatorSelectionForm.test.tsx
- frontend/fingertips-frontend/components/pages/results/Results.test.tsx
- frontend/fingertips-frontend/components/pages/results/index.tsx
Jira ticket: [DHSCFT-735](https://bjss-enterprise.atlassian.net/browse/DHSCFT-735)
Changes page number without reloading entire page
- useSearchParams hook from Next
- change url with history.replaceState (or history.pushState)
Existing tests still pass
> DHSCFT-735: pagination with shallow url navigation

- .github/workflows/e2e-and-api-tests.yml
- .github/workflows/update-screenshots.yml
Currently, you can run the 'Update Baseline Screenshots' workflow against `main`. I did not test this (and hope that with the branch protection rules, the commit that is created in that workflow cannot be applied directly to main).
This if statement hopefully makes things a bit clearer - it simply will not run the job if update-screenshots has been passed as true but the ref is the `main` branch.
Had hoped there was a way to limit the refs that can be used from a workflow dispatch action but it seems note: https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_dispatch Only option seems to be to use an `if`.
Temporarily pointed if statement against my branch, tried running the workflow and validated that the steps do not get run. …
> DHSCFT-TECH: Minor change to github branch protection for screenshots job

- frontend/fingertips-frontend/components/layouts/container/index.tsx
- frontend/fingertips-frontend/components/molecules/ModalPane/ModalPane.styles.tsx
- frontend/fingertips-frontend/components/molecules/ModalPane/ModalPane.test.tsx
- frontend/fingertips-frontend/components/molecules/ModalPane/ModalPane.tsx
- frontend/fingertips-frontend/components/molecules/ModalPane/ModalPaneCloseButton.tsx
- frontend/fingertips-frontend/components/molecules/ModalPane/__snapshots__/ModalPane.test.tsx.snap
- frontend/fingertips-frontend/context/ModalContext.test.tsx
- frontend/fingertips-frontend/context/ModalContext.tsx
Jira ticket: [DHSCFT-786](https://bjss-enterprise.atlassian.net/browse/DHSCFT-786)
A generic modal window pane for arbitrary content - in readiness for export chart preview and options
- Added modal context
- Added a useModal hook for ease of use
- Added a modal pane component and close button
Can be seen by adding...
```
const { setModal } = useModal();
useEffect(() => {
setModal({ title: 'This is a modal pane', content: <p>Hello world</p> });
}, [setModal]);
```
...to any mounted component e.g. `pages/home/index.tsx` to open the modal box.
> DHSCFT-786: Modal pane for displaying export options

- frontend/fingertips-frontend/components/molecules/ModalPane/ModalPaneCloseButton.tsx
- frontend/fingertips-frontend/components/molecules/ModalPane/__snapshots__/ModalPane.test.tsx.snap
Jira ticket: [DHSCFT-832](https://bjss-enterprise.atlassian.net/browse/DHSCFT-832)
The modal dialog button font size height and width changed from 14px to 20px to match figma design.
-  Button width and height changed.
-  Unit test snapshot updated.
> change close button size from 14px to 20px

- frontend/fingertips-frontend/components/atoms/FocusOnFragment/FocusOnFragment.test.tsx
- frontend/fingertips-frontend/components/atoms/FocusOnFragment/FocusOnFragment.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSearchForm/__snapshots__/IndicatorSearchForm.test.tsx.snap
- frontend/fingertips-frontend/components/forms/IndicatorSearchForm/index.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSelectionForm/index.tsx
- frontend/fingertips-frontend/components/forms/IndicatorSelectionForm/indicatorSelectionForm.test.tsx
- frontend/fingertips-frontend/components/layouts/container/index.tsx
- frontend/fingertips-frontend/components/molecules/SelectAreasFilterPanel/SelectAreasFilterPanel.test.tsx
- frontend/fingertips-frontend/components/molecules/SelectAreasFilterPanel/index.tsx
- frontend/fingertips-frontend/components/organisms/AreaFilterPane/AreaFilterPaneCheckbox.tsx
- frontend/fingertips-frontend/playwright/page-objects/pages/resultsPage.ts
- frontend/fingertips-frontend/playwright/tests/isolated_ui_tests/navigation_and_validation.spec.ts
Jira ticket: [DHSCFT-854](https://bjss-enterprise.atlassian.net/browse/DHSCFT-854)
Add a generic hook to use url fragments to maintain element focus when the page reloads due to selection change
- Added FocusOnFragment component
- Added id's to checkbox and select elements on results page
- Updated target paths to include a hash fragment
> DHSCFT-854: Keep items focused after selection triggers a reload

- .github/workflows/e2e-and-api-tests.yml
- frontend/fingertips-frontend/README.md
Jira ticket: [DHSCFT-939](https://bjss-enterprise.atlassian.net/browse/DHSCFT-939)
Added if else logic to the existing send slack message to handle sending a success message.
tested the if+else logic here - https://github.com/dhsc-govuk/FingertipsNext/actions/runs/15533395566/job/43727043984
see https://bjss.slack.com/archives/C08AZ71A98B/p1749468204490499 for discussions around the lack of access of the CI pipeline to the slack webhook secret
> DHSCFT-939 successful deployment sending a slack message

- frontend/fingertips-frontend/components/organisms/SpineChartLegend/SpineChartLegend.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartLegend/SpineChartLegend.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTable.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTableHeader.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTableHeader.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTableRow.test.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/SpineChartTableRow.tsx
- frontend/fingertips-frontend/components/organisms/SpineChartTable/index.tsx
- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsAreasViewPlots/TwoOrMoreIndicatorsAreasViewPlots.test.tsx
- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsAreasViewPlots/index.tsx
- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsEnglandViewPlots/TwoOrMoreIndicatorsEnglandViewPlots.test.tsx
- frontend/fingertips-frontend/components/viewPlots/TwoOrMoreIndicatorsEnglandViewPlots/index.tsx
- frontend/fingertips-frontend/components/viewPlots/ViewPlot.types.ts
- frontend/fingertips-frontend/components/views/TwoOrMoreIndicatorsAreasView/TwoOrMoreIndicatorsAreasView.test.tsx
- frontend/fingertips-frontend/components/views/TwoOrMoreIndicatorsAreasView/index.tsx
- frontend/fingertips-frontend/components/views/TwoOrMoreIndicatorsEnglandView/TwoOrMoreIndicatorsEnglandView.test.tsx
- frontend/fingertips-frontend/components/views/TwoOrMoreIndicatorsEnglandView/index.tsx
Jira ticket: [DHSCFT-1001](https://bjss-enterprise.atlassian.net/browse/DHSCFT-1001)
Removes the prop drilling for chart two indicator views.
All tests passing. Tested manually.
> DHSCFT-1001-Remove searchState prop drilling for chart

- frontend/fingertips-frontend/package-lock.json
- frontend/fingertips-frontend/package.json
Jira ticket: [DHSCFT-1124](https://bjss-enterprise.atlassian.net/browse/DHSCFT-1124)
see https://github.com/dhsc-govuk/FingertipsNext/security/dependabot/14 
this PR is to bump next to latest to address this sec vuln ^^^
we are on 15.3.1 and latest is 15.3.5
green pipelines
> DHSCFT-1124_bump_next_to_latest

- api/DHSC.FingertipsNext.Api.IntegrationTests/UserAuth/UserAuthenticationIntegrationTests.cs
- frontend/fingertips-frontend/playwright/page-objects/pages/uploadPage.ts
Jira ticket: [DHSCFT-886](https://bjss-enterprise.atlassian.net/browse/DHSCFT-886)
1.  loosen the upload e2e test so that it isnt looking for a specific number of rows in the table (as this will change) - just that there is at least 1 row in the table
2. address the API Integration tests failure
For 1 i have run the e2e CD tests locally against the deployed env and seen them pass with the fix/
> DHSCFT-886_loosen_upload_ui_e2e_assertion

- frontend/fingertips-frontend/components/molecules/AuthHeader/AuthHeader.styles.tsx
- frontend/fingertips-frontend/components/molecules/AuthHeader/index.tsx
- frontend/fingertips-frontend/components/molecules/Header/__snapshots__/Header.test.tsx.snap
Updates the auth button CSS to be less janky at non-1920px widths
screenshots show a variety of widths
not really something we're unit testing for
design approval pending
> update auth button positioning

- frontend/fingertips-frontend/package-lock.json
Jira ticket: None.
Updated eslint-related dependencies reported as vulnerable by NPM.
- Used `npm audit fix` to update vulnerable dependencies
CI validation in the build pipeline should be enough to verify there are no issues introduced.
> DHSCFT-TECH: Update vulnerable NPM dependencies

- api/DHSC.FingertipsNext.Modules.DataManagement.Service/DataManagementService.cs
- api/DHSC.FingertipsNext.Modules.DataManagement.Service/Models/LogClasses/BatchDeleteLog.cs
- api/DHSC.FingertipsNext.Modules.DataManagement.Service/Models/LogClasses/BatchUploadLog.cs
Jira ticket: [DHSCFT-1202](https://bjss-enterprise.atlassian.net/browse/DHSCFT-1202)
- Added an `Operation` field to `BatchUploadLog`
- Added an `Operation` field to `BatchDeleteLog`
- Set the `Operation` fields for the batch logs in `DataManagementService`
Ran the API as part of the Docker stack locally and then used the upload page to upload a file and then delete the batch:
Full upload log:
```json
{"Operation":"UploadFile","OriginalFileName":"valid.csv","Timestamp":"2025-07-31T16:00:04.9925613Z","UserId":"DsZbYClNPP7PaOfnzQKQZzC-BSF7KovQSqRBxL2WmPw","PublishedAt":"2035-01-01T00:00:00Z","BatchId":"12345_2025-07-31T16:00:04.902","IndicatorId":12345}
```
Full delete log:
```json …
```
> DHSCFT-1202: Add an Operation Field to Batch Logs

- frontend/fingertips-frontend/components/charts/ThematicMap/ThematicMap.tsx
- frontend/fingertips-frontend/components/charts/ThematicMap/ThematicMapTooltip/ThematicMapTooltip.test.tsx
- frontend/fingertips-frontend/components/charts/ThematicMap/ThematicMapTooltip/index.tsx
- frontend/fingertips-frontend/components/charts/ThematicMap/helpers/thematicMapHelpers.test.ts
- frontend/fingertips-frontend/components/charts/ThematicMap/helpers/thematicMapHelpers.ts
- frontend/fingertips-frontend/lib/chartHelpers/chartHelpers.test.ts
- frontend/fingertips-frontend/lib/chartHelpers/chartHelpers.ts
Removes the use of the to be deprecated `year` in favour of `datePeriod`
Manual testing to check it works as before
> DHSCFT-TECH: refactor out year for thematic map
