- .github/workflows/e2e-tests.yml
Jira ticket: [DHSCFT-208](https://bjss-enterprise.atlassian.net/browse/DHSCFT-208)
this is a followup fix to the original PR, just merged - https://github.com/dhsc-govuk/FingertipsNext/pull/71
- removed if statements in e2e-tests.yml template
- added missing step names
Once again we can only test this out by merging into main
> DHSCFT-208 - deploy frontend e2e test fix

- .github/workflows/fingertips-ai-search-setup.yml
- search-setup/package.json
Jira ticket: [DHSCFT-205](https://bjss-enterprise.atlassian.net/browse/DHSCFT-205)
Create a GitHub workflow to run the AI Search Setup project from the 'FingertipsNext' repo.
- Create a workflow which builds, runs, and tests the AI Search Setup
Workflow has been run from the branch successfully
> Create Azure AI Search Setup Workflow

- .github/workflows/e2e-tests.yml
- .github/workflows/fingertips-api-build.yml
- .github/workflows/fingertips-api-deploy.yml
- .github/workflows/fingertips-frontend-build.yml
- .github/workflows/fingertips-frontend-deploy.yml
Jira ticket: [DHSCFT-190](https://bjss-enterprise.atlassian.net/browse/DHSCFT-190)
Create a new GitHub workflow to build, test, and deploy the API component from the FingertipsNext repo.
- Create a build workflow to build and test the API project
- Create a deploy workflow to deploy the service to Azure Container Apps, after a successful build to the `main` branch (using workflow_run trigger)
- Refactor workflows to ensure path-based filtering, so CI is only triggered when changes are made to the relevant folders
Merge into main required prior to testing
> Create GitHub Actions Workflow for API Build and Deploy

- .github/workflows/deploy-container.yml
- .github/workflows/fingertips-api-deploy.yml
Jira ticket: [DHSCFT-276](https://bjss-enterprise.atlassian.net/browse/DHSCFT-276)
Pass the event name of the triggering workflow into the Deploy conditions to trigger from an appropriate event type
- Pass the event name of the triggering workflow to the resuable workflow and modify conditions
Unable to validate prior to merge
> Pass triggering workflow event name to the condition

- .github/workflows/fingertips-frontend-deploy.yml
Jira ticket: [DHSCFT-276](https://bjss-enterprise.atlassian.net/browse/DHSCFT-276)
Fix frontend deployment triggers
- Add the triggering event from the build workflow to the conditions of the deployment
API deployment has been updated and is now working
> Add triggering workflow event to frontend

- .github/workflows/fingertips-api-deploy.yml
- .github/workflows/fingertips-frontend-deploy.yml
Jira ticket: [DHSCFT-208](https://bjss-enterprise.atlassian.net/browse/DHSCFT-208)
Followup fix for [PR](https://github.com/dhsc-govuk/FingertipsNext/pull/83)
- changed conditional logic in frontend deploy and api deploy yml files to trigger e2e test correctly as they were incorrectly skipped in the above mentioned PR deploy job: https://github.com/dhsc-govuk/FingertipsNext/actions/runs/13027828654
Deploy job will be tested on merge
> DHSCFT-208_fix_for_deploy_e2e_tests

- .github/workflows/deploy-container.yml
- .github/workflows/e2e-tests.yml
We have added an ls command to debug why this test report isnt where it needs to be when the slack job runs
> DHSCFT-281 debug slack failure

- .github/workflows/deploy-container.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/fingertips-api-deploy.yml
- .github/workflows/fingertips-frontend-deploy.yml
Download the new test report so that slack job can send it
> DHSCFR-281 add download test artefact

- .github/workflows/fingertips-api-deploy.yml
- .github/workflows/fingertips-frontend-deploy.yml
Amend e2e deploy condition to run whether workflow_run was trigger on push or workflow_dispatch
- Update condition to run the e2e tests on workflow_dispatch triggers
> Amend e2e condition

- .github/workflows/e2e-tests.yml
Amend incorrect condition
- Update slack notification condition
> Amend condition

- frontend/fingertips-frontend/playwright/page-objects/basePage.ts
- frontend/fingertips-frontend/playwright/page-objects/pages/chartPage.ts
- frontend/fingertips-frontend/playwright/page-objects/pages/homePage.ts
- frontend/fingertips-frontend/playwright/page-objects/pages/resultsPage.ts
- frontend/fingertips-frontend/playwright/tests/search_results_and_view_chart.spec.ts
Jira ticket: [DHSCFT-313](https://bjss-enterprise.atlassian.net/browse/DHSCFT-313)
Added defensive code to stop playwright getting ahead of itself.
e2e tests pass locally against local and docker
> Feature/DHSCFT-313 Make e2e test stable

- frontend/fingertips-frontend/lib/search/indicatorSearchServiceMock.test.ts
- frontend/fingertips-frontend/package.json
- frontend/fingertips-frontend/playwright/page-objects/pages/homePage.ts
- frontend/fingertips-frontend/playwright/page-objects/pages/resultsPage.ts
- frontend/fingertips-frontend/playwright/tests/search_results_and_view_chart.spec.ts
Jira ticket: [DHSCFT-313](https://bjss-enterprise.atlassian.net/browse/DHSCFT-313)
Changed wait approach for clicking search on results page.
To validate the e2e tests are stable i ran them hundreds of times locally against localhost (mock service worker) and also hundreds of times using local docker.
> DHSCFT-313 change approach to waiting for search results

- .github/workflows/fingertips-workflow.yml
Jira ticket: [DHSCFT-318](https://bjss-enterprise.atlassian.net/browse/DHSCFT-318)
Fix manually run workflow (workflow_dispatch) trigger and conditions so that `db-deploy-dev` and `e2e-tests-dev` run when the workflow is manually run from branch
- Amend conditions in the relevant jobs for workflow_dispatch to trigger them
> Fix workflow_dispatch trigger

- .github/workflows/fingertips-workflow.yml
- api/Dockerfile
Jira ticket: [DHSCFT-318](https://bjss-enterprise.atlassian.net/browse/DHSCFT-318)
Ensure container push runs with push and PR changes
- Add conditions to the container push stages
- Ensure that deployments only happen from the `main` branch
Worklow run manually from branch successfully
> Fix container push conditions

- .github/workflows/e2e-tests.yml
Jira ticket: [DHSCFT-333](https://bjss-enterprise.atlassian.net/browse/DHSCFT-333)
In the PR - https://github.com/dhsc-govuk/FingertipsNext/pull/150- i had a logic error in the CD e2e test job skip logic (cant test that until we merge to main :( ) 
This PR is to fix it
> DHSCFT-333 - fix for job skip logic

- .github/workflows/e2e-tests.yml
- .github/workflows/fingertips-workflow.yml
Jira ticket: [DHSCFT-333](https://bjss-enterprise.atlassian.net/browse/DHSCFT-333)
Fix the frontend URL scoping issue when running the e2e tests in CD
Manual workflow kicked off and successfully ran the CI e2e tests here - https://github.com/dhsc-govuk/FingertipsNext/actions/runs/13387061790
> DHSCFT-333 - fix access of frontend URL in e2e test template

- api/DHSC.FingertipsNext.Modules.HealthData.Repository/Models/HealthMeasureModel.cs
- api/DHSC.FingertipsNext.Modules.HealthData.Schemas/HealthDataPoint.cs
- api/DHSC.FingertipsNext.Modules.HealthData.Schemas/HealthMeasure.cs
- api/DHSC.FingertipsNext.Modules.HealthData.UnitTests/Helpers/HealthMeasureModelHelper.cs
- api/definition/swagger.yaml
- database/fingertips-db/Tables/HealthMeasure.sql
- frontend/fingertips-frontend/components/organisms/Heatmap/heatmapUtil.test.ts
- frontend/fingertips-frontend/components/organisms/Heatmap/heatmapUtil.ts
- frontend/fingertips-frontend/components/organisms/LineChartTable/index.tsx
- frontend/fingertips-frontend/generated-sources/ft-api-client/models/AreaType.ts
- frontend/fingertips-frontend/generated-sources/ft-api-client/models/HealthDataPoint.ts
- frontend/fingertips-frontend/lib/chartHelpers/preparePopulationData.ts
Jira ticket: [DHSCFT-350](https://bjss-enterprise.atlassian.net/browse/DHSCFT-350)
Update HealthData table’s schema and API to account for null values, and make the frontend application deal with the situation gracefully.
- Update the HealthData table’s schema to mark the necessary fields as nullable
- Update the API’s Swagger definition to specify the necessary fields as optional
- Regenerate the frontend’s API clients
- Fix null references in Heatmap, PopulationData and PreparePopulationData
Build, test, e2e all passing successfully. Testing the site locally seems to be the same experience as prior to the change.
> Add support for missing values

- frontend/fingertips-frontend/playwright/tests/fully_integrated_e2e_tests/core_journeys.spec.ts
Jira ticket: [DHSCFT-354](https://bjss-enterprise.atlassian.net/browse/DHSCFT-354)
Change search term for e2e tests to pass
- Change search term to 'resident'
E2E local tests passing successfully on docker
> Change search term

- frontend/fingertips-frontend/components/molecules/Inequalities/BarChart/Table/__snapshots__/inequalitiesBarChartTable.test.tsx.snap
- frontend/fingertips-frontend/components/molecules/Inequalities/BarChart/Table/index.tsx
- frontend/fingertips-frontend/components/organisms/Inequalities/index.tsx
- frontend/fingertips-frontend/components/pages/chart/index.tsx
Jira ticket: [DHSCFT-221](https://bjss-enterprise.atlassian.net/browse/DHSCFT-221)
- Made suggested changes following BA review
> DHSCFT-221: BA review

- frontend/fingertips-frontend/package-lock.json
- frontend/fingertips-frontend/package.json
https://github.com/dhsc-govuk/FingertipsNext/security/dependabot/2
> update axios to at least v1.8.2

- api/DHSC.FingertipsNext.Modules.HealthData.Repository/HealthDataRepository.cs
Jira ticket: [DHSCFT-466](https://bjss-enterprise.atlassian.net/browse/DHSCFT-466)
Apply [mitigation](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#mitigations-1) to query per docs
- change query
behaviour checked locally
> update query to to use EF.Constant

- frontend/fingertips-frontend/components/atoms/HighlightText/HighlightText.test.tsx
- frontend/fingertips-frontend/components/atoms/HighlightText/__snapshots__/HighlightText.test.tsx.snap
- frontend/fingertips-frontend/components/atoms/HighlightText/index.tsx
- frontend/fingertips-frontend/components/molecules/AreaSuggestionPanel/AreaSuggestionPanel.test.tsx
- frontend/fingertips-frontend/components/molecules/AreaSuggestionPanel/__snapshots__/AreaSuggestionPanel.test.tsx.snap
- frontend/fingertips-frontend/components/molecules/AreaSuggestionPanel/index.tsx
Jira ticket: [DHSCFT-459](https://bjss-enterprise.atlassian.net/browse/DHSCFT-459)
-Fix bug with highlight search hint in lower case causing area suggestion to be malformed.
Tested against mock ai search and real ai search
> DHSCFT-459: fix issue with area suggestion and lower case

- .github/workflows/fingertips-workflow.yml
Add missing condition to DB build job
- Ensure DB build is triggered if Trend Analysis is updated
> DB build on trend analysis

- .github/workflows/e2e-tests.yml
Use a dynamic name for the playwright artifact to handle multiple uploads
- Add a new action to create a dynamic name with timestamp
- Use the artifact name in the upload
> Make artifact name dynamic

- frontend/fingertips-frontend/lib/apiClient/apiClientFactory.ts
Sets the revalidate timer to 0 to disable the caching
> DHSCFT-TECH: change caching to 10 mins

- database/fingertips-db/PostDeployment/PopulateFingertips.sql
Jira ticket: [DHSCFT-479](https://bjss-enterprise.atlassian.net/browse/DHSCFT-479)
Fix an issue where districts and UA UAs had no parent areas
Fix an issue in populatefingertips.sql
Run the db setup and check the issue is fixed in the database
> fix issue with missing parent areas for UAs

- .github/workflows/e2e-tests.yml
- frontend/fingertips-frontend/README.md
Jira ticket: [DHSCFT-478](https://bjss-enterprise.atlassian.net/browse/DHSCFT-478)
fix for artefact name step to always run
> DHSCFT-478 fix for artefact name

- .github/workflows/fingertips-workflow.yml
Add missing needs clause to trend analysis job in the workflow
- Add missing needs clause
> Add needs to trend job

- database/fingertips-db/PostDeployment/PopulateFingertips.sql
- database/fingertips-db/Tables/AreaDimension.sql
Add area type code column to the AreaDimension table and populate it with data
Deplot the DB locally and ensure the data looks correct
> add area type column to the AreaDimension table and populate it

- frontend/fingertips-frontend/playwright/tests/isolated_ui_tests/navigation_and_validation.spec.ts
Jira ticket: [DHSCFT-538](https://bjss-enterprise.atlassian.net/browse/DHSCFT-538)
Removed the duplicate validation check as its already tested in unit tests and elsewhere in the ui testing
> DHSCFT-538 fix ui flake

- .github/workflows/fingertips-workflow.yml
- trend-analysis/TrendAnalysisApp/nuget.config
Cache nuget dependencies to improve Trend Analysis duration. Currently, nuget packages are bing downloaded every time the job runs.
- Add nuget cache action to the workflow
Tested manually against the branch and duration has improved by 8-10mins
> Add nuget caching to trend analysis

- frontend/fingertips-frontend/app/results/page.tsx
- frontend/fingertips-frontend/components/pages/results/index.tsx
Jira ticket: [DHSCFT-458](https://bjss-enterprise.atlassian.net/browse/DHSCFT-458)
- Default search term to empty string
- Omit the word `for` in the title if search term is blank
> DHSCFT-458: Show results when no search term is supplied

- frontend/fingertips-frontend/components/views/TwoOrMoreIndicatorsEnglandView/TwoOrMoreIndicatorsEnglandView.test.tsx
Jira ticket: [DHSCFT-618](https://bjss-enterprise.atlassian.net/browse/DHSCFT-618)
- Added test to validate error was thrown for incorrect meta data in TwoOrMoreIndicatorsEnglandView.test.tsx
- Added additional mock indicator data to TwoOrMoreIndicatorsEnglandView.test.tsx
- Tests pass
> updated tests

- frontend/fingertips-frontend/components/organisms/SpineChart/index.tsx
Jira ticket: [DHSCFT-155](https://bjss-enterprise.atlassian.net/browse/DHSCFT-155)
- Spine bars are stacking not overlapping, so minus/add quartiles to/from best/worst
> DHSCFT-155: Add shapes to spine chart: plotting issues

- frontend/fingertips-frontend/components/organisms/SpineChart/index.tsx
Didn't get the change to add my review comments. These would be my suggestions.
I found the naming misleading - hopefully this is clearer.
Screenshot testing should still pass. Also checked manually that the spine charts still match up nicely.
> DHSCFT-155: Minor refactor to how we generate spine chart data

- frontend/fingertips-frontend/components/hooks/useMoreRowsWhenScrolling.test.tsx
- frontend/fingertips-frontend/components/hooks/useMoreRowsWhenScrolling.ts
Jira ticket: [DHSCFT-656](https://bjss-enterprise.atlassian.net/browse/DHSCFT-656)
- Simplified the hook for detecting if more rows need to render
- Removed the scroll event, it just keeps checking if trigger is in view until there is no more to show
Testing and functionality hardly changed
> DHSCFT-656: Simplified the useMoreRowsWhenScrolling hook, to solve issues stuck in loading mode

- frontend/fingertips-frontend/package-lock.json
- frontend/fingertips-frontend/package.json
Jira ticket: [DHSCFT-674](https://bjss-enterprise.atlassian.net/browse/DHSCFT-674)
Update next js package 
Pipelines pass
> 674_update_next_js

- frontend/fingertips-frontend/package-lock.json
- frontend/fingertips-frontend/package.json
Jira ticket: [DHSCFT-684](https://bjss-enterprise.atlassian.net/browse/DHSCFT-684)
update react and react_dom + their types libraries to latest
pipelines pass
> DHSCFT-684_bump_react and reactdom

- frontend/fingertips-frontend/components/molecules/Header/Header.test.tsx
- frontend/fingertips-frontend/components/molecules/Header/__snapshots__/Header.test.tsx.snap
- frontend/fingertips-frontend/components/molecules/Header/index.tsx
Jira ticket: [DHSCFT-641](https://bjss-enterprise.atlassian.net/browse/DHSCFT-641)
- Add link to header to return to home page
- Tests pass, manual validation
> return to home page

- frontend/fingertips-frontend/components/molecules/Inequalities/InequalitiesTrend/index.tsx
- frontend/fingertips-frontend/components/organisms/Inequalities/inequalitiesHelpers.test.ts
- frontend/fingertips-frontend/components/organisms/Inequalities/inequalitiesHelpers.ts
Jira ticket: [DHSCFT-654](https://bjss-enterprise.atlassian.net/browse/DHSCFT-654)
Second
and the table order
Fix a bug that was found after the ticket was merged.
> reorder move out

- frontend/fingertips-frontend/components/molecules/AreaSuggestionPanel/AreaSuggestionPanel.test.tsx
- frontend/fingertips-frontend/components/molecules/AreaSuggestionPanel/index.tsx
https://bjss-enterprise.atlassian.net/browse/DHSCFT-639
When England is selected from the area search results, the state is now populated in the same way as it would be from the area filter.
> populate state fully when england selected

- frontend/fingertips-frontend/components/organisms/LineChartTable/LineChartTable.test.tsx
- frontend/fingertips-frontend/components/organisms/LineChartTable/index.tsx
Jira ticket: [DHSCFT-567](https://bjss-enterprise.atlassian.net/browse/DHSCFT-567)
- Only show group column in line chart table when an area has been selected (checkbox)
- manual validation, tests pass
> conditionally render group column

- frontend/fingertips-frontend/jest.config.ts
Jira ticket: [DHSCFT-762](https://bjss-enterprise.atlassian.net/browse/DHSCFT-762)
- Add .tsx
- Adjust coverage limit thresholds
> DHSCFT-672: Code coverage limits and inclusions

- frontend/fingertips-frontend/lib/downloadHelpers/convertToCsv.test.ts
- frontend/fingertips-frontend/lib/downloadHelpers/convertToCsv.ts
Jira ticket: [DHSCFT-775](https://bjss-enterprise.atlassian.net/browse/DHSCFT-775)
- pre-requisite for the export to csv functionality
- trying not to add external library for something fairly simple
- Added convert data arrays to csv string
- Added unit tests passing incorrect types and extra commas, quotes, line breaks etc
> DHSCFT-775: convert to csv utility function

- frontend/fingertips-frontend/components/pages/results/index.tsx
ronseal
https://bjss-enterprise.atlassian.net/browse/DHSCFT-594
https://bjss-enterprise.atlassian.net/browse/DHSCFT-778
manually tested
> DHSCFT-778 add word wrap to search result title

- search-setup/src/constants.ts
- search-setup/src/utils/indexHelper.ts
Jira ticket: [DHSCFT-721](https://bjss-enterprise.atlassian.net/browse/DHSCFT-721)
- Fixed the test failing due to the escape function adding more escape characters than expected to the string
Tests passing locally
> DHSCFT-721: Fix search setup integration test failure

- frontend/fingertips-frontend/components/molecules/AreaSelectedPill/index.tsx
- frontend/fingertips-frontend/components/molecules/AreaSuggestionPanel/__snapshots__/AreaSuggestionPanel.test.tsx.snap
- frontend/fingertips-frontend/components/molecules/AreaSuggestionPanel/index.tsx
- frontend/fingertips-frontend/lib/areaFilterHelpers/formatAreaName.test.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/formatAreaName.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/generateAreaDisplayString.test.ts
- frontend/fingertips-frontend/lib/areaFilterHelpers/generateAreaDisplayString.ts
Jira ticket: [DHSCFT-785](https://bjss-enterprise.atlassian.net/browse/DHSCFT-785)
- Updated area suggestion to display postcode for areas that have their postcode available
> DHSCFT-785: Display postcode in area suggestions

- .github/workflows/deploy-container.yml
Jira ticket: [DHSCFT-794](https://bjss-enterprise.atlassian.net/browse/DHSCFT-794)
Add missing runner tag for self-hosted runner on terraform deploy job
- Use environment specific tag for self-hosted runner
> Correct runner tag

- api/DHSC.FingertipsNext.Modules.HealthData/HttpClientScripts/test-indicators-benchmark-quintiles.http
Jira ticket: [DHSCFT-627](https://bjss-enterprise.atlassian.net/browse/DHSCFT-627)
Fix a failing HTTP script overlooked in previous PR
- Fix test. It was not accounting for empty areas in results..
> DHSCFT-627 - fix http script test

- DataCreator/DataCreator.Tests/DataCreator.Tests.csproj
- DataCreator/DataCreator.Tests/DataFileReaderTests.cs
Jira ticket: [DHSCFT-764](https://bjss-enterprise.atlassian.net/jira/software/projects/DHSCFT/boards/823?selectedIssue=DHSCFT-764)
This adds a unit test for the work associated with this ticket
- Unit test for validating that CCG and STP areas are excluded from results
> DHSCFT-764: Added unit test

- frontend/fingertips-frontend/package.json
Jira ticket: [DHSCFT-1033)](https://bjss-enterprise.atlassian.net/browse/DHSCFT-1033)
Fixing bug introduced in previous [PR](https://github.com/dhsc-govuk/FingertipsNext/pull/679
) with running e2e tests against CD:
Tested fixed command locally as best as possible - no longer throwing previous error
> DHSCFT-1033 - fix bug with running the e2e tests in CD

- frontend/fingertips-frontend/lib/timePeriodHelpers/getTimePeriodLabels.test.ts
- frontend/fingertips-frontend/lib/timePeriodHelpers/getTimePeriodLabels.ts
Jira ticket: [DHSCFT-1070](https://bjss-enterprise.atlassian.net/browse/DHSCFT-1070)
Time period helper function.
Added unit tests for the valid combination of periodType and Frequency
> [DHSCFT-1070] time period helper function

- .github/workflows/e2e-and-api-tests.yml
- .github/workflows/fingertips-workflow.yml
- api/DHSC.FingertipsNext.Api/Middleware/FingertipsUserAuthentication.cs
Jira ticket: [DHSCFT-950](https://bjss-enterprise.atlassian.net/browse/DHSCFT-950)
- Adding external ID configuration into environment variables for web app and api.
n/a
> Configuring web apps with external ID configuration

- .github/workflows/fingertips-workflow.yml
add missing comma to pipeline script
> add missing comma

- frontend/fingertips-frontend/components/organisms/LineChart/helpers/__snapshots__/generateStandardLineChartOptions.test.ts.snap
- frontend/fingertips-frontend/components/organisms/LineChart/helpers/addShowHideLinkedSeries.test.ts
- frontend/fingertips-frontend/components/organisms/LineChart/helpers/filterHealthDataByPeriod.ts
- frontend/fingertips-frontend/components/organisms/LineChart/helpers/generateSeriesData.test.ts
- frontend/fingertips-frontend/components/organisms/LineChart/helpers/generateSeriesData.ts
- frontend/fingertips-frontend/components/organisms/LineChart/helpers/generateStandardLineChartOptions.ts
- frontend/fingertips-frontend/components/organisms/LineChart/helpers/generateTooltip.test.ts
- frontend/fingertips-frontend/components/organisms/LineChart/helpers/generateTooltip.ts
- frontend/fingertips-frontend/components/organisms/LineChartTable/__snapshots__/LineChartTable.test.tsx.snap
- frontend/fingertips-frontend/components/organisms/LineChartTable/index.tsx
- frontend/fingertips-frontend/lib/chartHelpers/chartHelpers.test.ts
- frontend/fingertips-frontend/lib/chartHelpers/chartHelpers.ts
Jira ticket: [DHSCFT-1051](https://bjss-enterprise.atlassian.net/browse/DHSCFT-1051)
Fixes Cumulative quarters.
Tested manually
> DHSCFT-1051: Fix lineChart and table for cumulative quarters

- frontend/fingertips-frontend/.gitignore
- frontend/fingertips-frontend/playwright/page-objects/pages/uploadPage.ts
- frontend/fingertips-frontend/playwright/testHelpers/genericTestUtilities.ts
- frontend/fingertips-frontend/playwright/tests/fully_integrated_e2e_tests/data_upload.spec.ts
- frontend/fingertips-frontend/upload/components/organisms/BatchListTable/__snapshots__/BatchListTable.test.tsx.snap
- frontend/fingertips-frontend/upload/components/organisms/BatchListTable/index.tsx
Jira ticket: [DHSCFT-1158](https://bjss-enterprise.atlassian.net/browse/DHSCFT-1158)
tiny PR just to get the upload UI e2e test back working
> re-enable the upload test with authentication
